attraction_type = input("What type of attraction (Sports and Adventure, Museums and Historic Sites, Eat and Drink, Nightlife and Entertainment) do you want? ").lower()
entry = input("Does the attraction have to be free or it can be paid? ").lower()
timing = input("Do you want the attraction to be open, day(until 9-10 PM) or extended(until Midnight)? ").lower()
age_restriction = input("Do you want any age restrictions, no (None) or only adults (Adults)? ").lower()
acommodation = input("Do you want outdoor or indoor? ").lower()
